name: Build

on:
  push:
  pull_request:
    paths-ignore:
      - "**.md"

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: linux_ARMv7,
              c_compiler: gcc-12-arm-linux-gnueabihf,
              cxx_compiler: g++-12-arm-linux-gnueabihf,
              c_flag: arm-linux-gnueabihf-gcc-12,
              cxx_flag: arm-linux-gnueabihf-g++-12,
            }
          - {
              name: linux_ARMv8,
              c_compiler: gcc-12-aarch64-linux-gnu,
              cxx_compiler: g++-12-aarch64-linux-gnu,
              c_flag: aarch64-linux-gnu-gcc-12,
              cxx_flag: aarch64-linux-gnu-g++-12,
            }
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake libssl-dev

      - name: Install cross-compiler
        run: |
          sudo apt-get install -y ${{ matrix.config.c_compiler }} ${{ matrix.config.cxx_compiler }}
          export CC=/usr/bin/${{ matrix.config.c_flag }} CXX=/usr/bin/${{ matrix.config.cxx_flag }}
          export CMAKE_INCLUDE_PATH=/usr/include

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_C_COMPILER=/usr/bin/${{ matrix.config.c_flag }} \
            -DCMAKE_CXX_COMPILER=/usr/bin/${{ matrix.config.cxx_flag }} \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          make
