name: Build

on:
  push:
  pull_request:
    paths-ignore:
      - "**.md"

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: linux_ARMv7,
              c_compiler: gcc-12-arm-linux-gnueabihf,
              cxx_compiler: g++-12-arm-linux-gnueabihf,
              c_flag: arm-linux-gnueabihf-gcc-12,
              cxx_flag: arm-linux-gnueabihf-g++-12,
              vcpkg: arm-linux,
            }
          - {
              name: linux_ARMv8,
              c_compiler: gcc-12-aarch64-linux-gnu,
              cxx_compiler: g++-12-aarch64-linux-gnu,
              c_flag: aarch64-linux-gnu-gcc-12,
              cxx_flag: aarch64-linux-gnu-g++-12,
              vcpkg: arm64-linux,
            }
          # - {
          #     name: linux_x86,
          #     c_compiler: gcc-12,
          #     cxx_compiler: g++-12,
          #     c_flag: gcc-12,
          #     cxx_flag: g++-12,
          #     vcpkg: x86-linux,
          #   }
          - {
              name: linux_x86_64,
              c_compiler: gcc-12,
              cxx_compiler: g++-12,
              c_flag: gcc-12,
              cxx_flag: g++-12,
              vcpkg: x64-linux-release,
            }
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Install cross-compiler
        run: |
          sudo apt-get install -y ${{ matrix.config.c_compiler }} ${{ matrix.config.cxx_compiler }}
          export CC=/usr/bin/${{ matrix.config.c_flag }} CXX=/usr/bin/${{ matrix.config.cxx_flag }}

      - name: Install vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git --depth=1
          bash ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
          vcpkg install openssl:${{ matrix.config.vcpkg }}

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_C_COMPILER=/usr/bin/${{ matrix.config.c_flag }} \
            -DCMAKE_CXX_COMPILER=/usr/bin/${{ matrix.config.cxx_flag }} \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin/
          make

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: KnowledgeCool_${{ matrix.config.name }}
          path: build/bin
